pipeline {
    agent { docker { image 'node:16.17.1-alpine' } }
    parameters {
      string(name: 'access_token', defaultValue: '', description: 'Access token for VOS')
      string(name: 'channel_url', defaultValue: '', description: 'Channel url')
    }
    stages {
        stage('build') {
            steps {
                sh 'node --version'
                echo "Access Token ${params.access_token}"
                echo "Access Token ${params.channel_url}"
            }
        }
        stage('Test slate') {
            steps {
              script {
                sh "node jobs/slate/steps/slate.js"
              }
            }
        }
    }
}