pipeline {
    agent { docker { image 'node:16.17.1-alpine' } }
    stages {
        stage('build') {
            steps {
                sh 'node --version'
            }
        }
        stage('Test slate') {
            steps {
              script {
                sh "node jobs/slate/slate.js"
              }
            }
        }
    }
}