def access_token = 'initial'
pipeline {
    agent { docker { image 'node:16.17.1-alpine' } }
    stages {
        stage('build') {
            steps {
                sh 'node --version'
            }
        }
        stage('Get Access Key') {
            steps {
              script {
                sh 'ls'
                access_token = sh(script: 'node jobs/auth/steps/auth_step.js', returnStdout: true)
              }
            }
        }
        stage('Test auth') {
            steps {
                script {
                  sh """node jobs/auth/steps/test1.js ${access_token}"""
                }
            }
        }
        stage('Start tests') {
            steps {
                script {
                  build 'second-pipeline'
                }
            }
        }
    }
}