def access_token = 'initial'
def channel_url = '0.0.0.0'
pipeline {
    agent { docker { image 'node:16.17.1-alpine' } }
    environment {
      CRED1 = credentials('TEST_CRED')
      CRED2 = credentials('CRED_TEST2')
    }
    parameters {
      string(name: 'channel', defaultValue: '', description: 'Channel to test')
    }
    stages {
        stage('build') {
            steps {
                sh 'node --version'
                echo "Channel to test: ${params.channel} ${CRED1} ${CRED2}"
            }
        }
        stage('Get Access Key') {
            steps {
              script {
                access_token = sh(script: 'node jobs/auth/steps/auth_step.js', returnStdout: true)
              }
            }
        }
        stage('Test auth') {
            steps {
                script {
                  sh """node jobs/auth/steps/test1.js ${access_token}"""
                }
            }
        }
        stage('Start FFMPEG SRT to MPEGTS copy') {
            steps {
                script {
                  channel_url = sh(script: 'node jobs/auth/steps/srt_step.js', returnStdout: true)
                }
            }
        }
        stage('Start slate tests pipeline') {
            steps {
                script {
                  build job: 'second-pipeline/master', parameters: [string(name: 'access_token', value: "${access_token}"), string(name: 'channel_url', value: "${channel_url}")]
                }
            }
        }
    }
}