def access_token = 'initial'
def channel_url = '0.0.0.0'
pipeline {
    agent { docker { image 'node:16.17.1-alpine' } }
    stages {
        stage('build') {
            steps {
                sh 'node --version'
            }
        }
        stage('Get Access Key') {
            steps {
              script {
                access_token = sh(script: 'node jobs/auth/steps/auth_step.js', returnStdout: true)
              }
            }
        }
        stage('Test auth') {
            steps {
                script {
                  sh """node jobs/auth/steps/test1.js ${access_token}"""
                }
            }
        }
        stage('Start FFMPEG SRT to MPEGTS copy') {
            steps {
                script {
                  channel_url = sh(script: 'node jobs/auth/steps/srt_step.js', returnStdout: true)
                }
            }
        }
        stage('Start slate tests pipeline') {
            steps {
                script {
                  build 'second-pipeline/master'
                }
            }
        }
    }
}